spring:
  datasource:
    password: ${ORDER_SERVICE_POSTGRES_PASSWORD}
    username: ${ORDER_SERVICE_POSTGRES_USER}
    driver-class-name:
    url: jdbc:postgresql://${ORDER_SERVICE_POSTGRES_HOST}:${ORDER_SERVICE_POSTGRES_PORT}/${ORDER_SERVICE_POSTGRES_DB}
    hikari:
      driver-class-name: org.postgresql.Driver


environment:
  host: http://127.0.0.1
  kafka:
    address: ${AUTH_SERVICE_KAFKA_HOST}:${AUTH_SERVICE_KAFKA_PORT}

user-service:
  url: http://user-service:8071

