spring:
  application:
    name: order-service

  datasource:
    password: ${ORDER_SERVICE_POSTGRES_PASSWORD}
    username: ${ORDER_SERVICE_POSTGRES_USER}
    driver-class-name:
    url: jdbc:postgresql://${ORDER_SERVICE_POSTGRES_HOST}:${ORDER_SERVICE_POSTGRES_PORT}/${ORDER_SERVICE_POSTGRES_DB}
    hikari:
      driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: ${environment.kafka.address}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: payment-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'

site:
  domain:
    url: ${environment.host}:${server.port}

server:
  port: 8081

environment:
  host: http://127.0.0.1
  kafka:
    address: localhost:9092

user-service:
  url: http://localhost:8071


