create table IF NOT EXISTS orders
(
    id           bigint generated by default as identity
    primary key,
    created_dttm timestamp(6) default CURRENT_TIMESTAMP not null,
    updated_at   timestamp(6) default CURRENT_TIMESTAMP not null,
    version      bigint       default 1                 not null
    constraint orders_version_check
    check (version > 0)
    constraint orders_version_check1
    check (version >= 1),
    status       varchar(255)                           not null
    constraint orders_status_check
    check ((status)::text = ANY
((ARRAY ['NEW'::character varying, 'PROCESSING'::character varying, 'SHIPPED'::character varying, 'DELIVERED'::character varying, 'CANCELLED'::character varying])::text[])),
    user_id      varchar(255)                                 not null
    );

comment on column orders.id is 'Identifier';

comment on column orders.created_dttm is 'Format ISO 8601: YYYY-MM-DD hh:mm:ss.000000';

comment on column orders.updated_at is 'Format ISO 8601: YYYY-MM-DD hh:mm:ss.000000';

comment on column orders.version is 'large range number from -9223372036854775808 to +9223372036854775807';

comment on column orders.status is 'Current status of the order';

comment on column orders.user_id is 'Unique identifier of the user who placed the order';

CREATE INDEX idx_orders_user_id ON orders(user_id);
CREATE INDEX idx_orders_status ON orders(status);
