create table IF NOT EXISTS items
(
    id           bigint generated by default as identity
    primary key,
    created_dttm timestamp(6) default CURRENT_TIMESTAMP not null,
    updated_at   timestamp(6) default CURRENT_TIMESTAMP not null,
    version      bigint       default 1                 not null
    constraint items_version_check
    check (version > 0)
    constraint items_version_check1
    check (version >= 1),
    name         varchar(100)                           not null,
    price        double precision                       not null
    );

comment on column items.id is 'Identifier';

comment on column items.created_dttm is 'Format ISO 8601: YYYY-MM-DD hh:mm:ss.000000';

comment on column items.updated_at is 'Format ISO 8601: YYYY-MM-DD hh:mm:ss.000000';

comment on column items.version is 'large range number from -9223372036854775808 to +9223372036854775807';

comment on column items.name is 'Name of the item, must be between 2 and 100 characters';

comment on column items.price is 'Price of the item, must be greater than 0';

CREATE INDEX uq_items_name ON items(name);
