create table IF NOT EXISTS order_items
(
    id           bigint generated by default as identity
    primary key,
    created_dttm timestamp(6) default CURRENT_TIMESTAMP not null,
    updated_at   timestamp(6) default CURRENT_TIMESTAMP not null,
    version      bigint       default 1                 not null
    constraint chk_order_items_version
    check (version >= 1),
    quantity     bigint                                 not null
    constraint chk_order_items_quantity
    check (quantity >= 0),
    item_id      bigint                                 not null
    constraint fk_order_items_item
    references items,
    order_id     bigint                                 not null
    constraint fk_order_items_order
    references orders
    );

comment on column order_items.id is 'Identifier';

comment on column order_items.created_dttm is 'Format ISO 8601: YYYY-MM-DD hh:mm:ss.000000';

comment on column order_items.updated_at is 'Format ISO 8601: YYYY-MM-DD hh:mm:ss.000000';

comment on column order_items.version is 'large range number from -9223372036854775808 to +9223372036854775807';

comment on column order_items.quantity is 'Quantity of the item in this order';

comment on column order_items.item_id is 'Item being ordered';

comment on column order_items.order_id is 'Order to which this item belongs';

CREATE INDEX idx_order_items_order_id ON order_items(order_id);
CREATE INDEX idx_order_items_item_id ON order_items(item_id);
